title       = "foody"
baseURL     = "https://foody-cli.tamnd.com/"
description = "A command line for foody."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/foody-cli"
